volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: ${DOCKERHUB_USERNAME}/kittygram_backend
    env_file: .env
    volumes:
      - static:/app/collected_static
      - media:/app/media
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: ${DOCKERHUB_USERNAME}/kittygram_frontend
    volumes:
      - static:/app/result_build

  gateway:
    image: ${DOCKERHUB_USERNAME}/kittygram_gateway
    ports:
      - "9000:80"
    volumes:
      - static:/static
      - media:/media
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_completed_successfully
